# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-04 16:26
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('addition_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='GameResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player', models.TextField()),
                ('score', models.IntegerField()),
                ('place', models.SmallIntegerField()),
                ('starting_position', models.SmallIntegerField()),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mahjong_statboard.Game')),
            ],
        ),
        migrations.CreateModel(
            name='Instance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('description', models.TextField(blank=True)),
                ('game_storage', models.CharField(choices=[('local', 'local'), ('pantheon', 'pantheon')], default='local', max_length=16)),
                ('pantheon_id', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating_type', models.CharField(max_length=32)),
                ('instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mahjong_statboard.Instance')),
            ],
        ),
        migrations.CreateModel(
            name='Stats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player', models.TextField()),
                ('value', models.TextField()),
                ('game', models.TextField()),
                ('instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mahjong_statboard.Instance')),
                ('rating', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mahjong_statboard.Rating')),
            ],
        ),
        migrations.AddField(
            model_name='game',
            name='instance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mahjong_statboard.Instance'),
        ),
        migrations.AddField(
            model_name='game',
            name='posted_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
