# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-31 11:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mahjong_statboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stats',
            name='place',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rating',
            name='rating_type_id',
            field=models.CharField(choices=[('average_place', 'Среднее место'), ('average_place_series', 'Серия по среднему месту'), ('tenhou_rating', 'Tenhou rating')], max_length=32),
        ),
    ]
