# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-19 16:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mahjong_statboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stats',
            name='game',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mahjong_statboard.Game'),
        ),
    ]
