# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-24 13:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mahjong_statboard', '0002_auto_20170719_1644'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rating',
            name='series_len',
            field=models.PositiveIntegerField(blank=True, help_text='Работает только если рейтинг является серией', null=True),
        ),
        migrations.AddField(
            model_name='rating',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rating',
            name='weight',
            field=models.IntegerField(default=0, help_text='Порядок сортировки'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='rating',
            name='rating_type',
            field=models.CharField(choices=[('Average place', 'Average place'), ('10 games series', '10 games series')], max_length=32),
        ),
    ]
