# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-10 10:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mahjong_statboard', '0003_auto_20170809_1628'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='hidden',
            field=models.BooleanField(default=False),
        ),
    ]
