# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-17 17:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mahjong_statboard', '0004_player_hidden'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='state',
            field=models.CharField(choices=[('inqueue', 'In queue for counting'), ('counting', 'Counting'), ('actual', 'Actual')], default='inqueue', max_length=16),
        ),
    ]
