# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-18 13:01
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mahjong_statboard', '0005_rating_state'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='game',
            options={'ordering': ('-date', '-addition_time')},
        ),
        migrations.AlterModelOptions(
            name='gameresult',
            options={'ordering': ('starting_position',)},
        ),
        migrations.AddField(
            model_name='instance',
            name='admins',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='rating',
            name='rating_type_id',
            field=models.CharField(choices=[('average_place', 'Среднее место'), ('average_place_series', 'Серия по среднему месту'), ('tenhou_rating', 'Tenhou rating'), ('average_score', 'Средний счет'), ('games_count', 'Число игр'), ('max_score', 'Максимальный счет'), ('score_sum', 'Сумма очков')], max_length=32),
        ),
        migrations.AlterField(
            model_name='rating',
            name='weight',
            field=models.IntegerField(default=999, help_text='Порядок сортировки'),
        ),
    ]
