# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-18 15:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mahjong_statboard', '0006_auto_20170918_1301'),
    ]

    operations = [
        migrations.AddField(
            model_name='instance',
            name='title',
            field=models.TextField(blank=True),
        ),
    ]
