# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-15 13:55
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mahjong_statboard', '0008_instancedomain'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='days_number',
            field=models.PositiveIntegerField(blank=True, help_text='Брать игры за последние N дней', null=True),
        ),
        migrations.AlterField(
            model_name='instance',
            name='admins',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
