# Generated by Django 2.0 on 2017-12-04 15:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mahjong_statboard', '0009_auto_20171115_1355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='instance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mahjong_statboard.Instance'),
        ),
        migrations.AlterField(
            model_name='game',
            name='posted_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='gameresult',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mahjong_statboard.Game'),
        ),
        migrations.AlterField(
            model_name='gameresult',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mahjong_statboard.Player'),
        ),
        migrations.AlterField(
            model_name='instancedomain',
            name='instance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='domains', to='mahjong_statboard.Instance'),
        ),
        migrations.AlterField(
            model_name='player',
            name='instance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mahjong_statboard.Instance'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='instance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mahjong_statboard.Instance'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='rating_type_id',
            field=models.CharField(choices=[('average_place', 'Среднее место'), ('average_place_series', 'Серия по среднему месту'), ('tenhou_rating', 'Tenhou rating'), ('tenhou_rating_no_adj', 'Tenhou rating(без затухания)'), ('average_score', 'Средний счет'), ('games_count', 'Число игр'), ('max_score', 'Максимальный счет'), ('score_sum', 'Сумма очков'), ('last_game_date', 'Дата последней игры')], max_length=32),
        ),
        migrations.AlterField(
            model_name='stats',
            name='game',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='mahjong_statboard.Game'),
        ),
        migrations.AlterField(
            model_name='stats',
            name='instance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mahjong_statboard.Instance'),
        ),
        migrations.AlterField(
            model_name='stats',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mahjong_statboard.Player'),
        ),
        migrations.AlterField(
            model_name='stats',
            name='rating',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mahjong_statboard.Rating'),
        ),
    ]
