# Generated by Django 2.0 on 2017-12-04 16:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mahjong_statboard', '0010_auto_20171204_1541'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameresult',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mahjong_statboard.Game'),
        ),
        migrations.AlterField(
            model_name='instancedomain',
            name='instance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='domains', to='mahjong_statboard.Instance'),
        ),
        migrations.AlterField(
            model_name='stats',
            name='game',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mahjong_statboard.Game'),
        ),
        migrations.AlterField(
            model_name='stats',
            name='instance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mahjong_statboard.Instance'),
        ),
        migrations.AlterField(
            model_name='stats',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mahjong_statboard.Player'),
        ),
        migrations.AlterField(
            model_name='stats',
            name='rating',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mahjong_statboard.Rating'),
        ),
    ]
