# Generated by Django 2.0 on 2018-01-10 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mahjong_statboard', '0011_auto_20171204_1615'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='archived',
            field=models.BooleanField(default=False),
        ),
    ]
